fix: handle remaining JNI calls error handling
bugsnag/bugsnag-android pull request #1092
Opened 2021-01-26 17:25 UTC by fractalwrench

## Goal

## Design

## Changeset

## Testing

2021-01-29 08:44 UTC, kstenerud requested changes
There are many functions that have existing/new leak issues that can be fixed with c-style RAII. We should probably just convert everything over once and for all...

2021-01-29 08:44 UTC, kstenerud commented on bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
> +    return;
Will `crumb_type` leak here?

2021-01-29 08:44 UTC, kstenerud commented on bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
> +      return;
`trace` will leak here

2021-01-29 08:44 UTC, kstenerud commented on bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
> +    return;
These will leak things as well. This should probably be a c-style RAII

2021-01-29 08:44 UTC, kstenerud commented on bugsnag-plugin-android-ndk/src/main/jni/metadata.c
> +    return;
These will leak things. Should be c-style RAII

2021-01-29 14:27 UTC, fractalwrench commented
Thanks @kstenerud - I've updated the changeset so that the functions use RAII where it seemed appropriate.

2021-02-01 08:18 UTC, kstenerud approved these changes
LGTM!

2021-02-01 09:10 UTC, merged