Rework startup threading
bugsnag/bugsnag-android pull request #2069
Opened 2024-08-12 09:16 UTC by lemnik

## Goal
Improve the threading during startup and reduce the overheads.

## Design
Replaced the various layers of startup tasks with a dedicated structure. The `RunnableProvider` class replaces the previously used `Future`, `SafeFuture` and `Callable` / `Runnable` tasks. The `RunnableProvider` safely computes values on background threads, and blocks only when required while also avoiding running the work (such as IO) on the main thread.

## Testing
Updated tests to handle the new structures, and relied on existing tests along with manual testing with `StrictMode` using `detectAll()`.

2024-09-05 15:48 UTC, tomlongridge commented on bugsnag-android-core/src/main/java/com/bugsnag/android/StorageModule.kt
> +    fun loadUser(initialUser: User): Provider<UserState> = provider {
This appears to be doubly-wrapped in providers - what's the reason for UserStore being handled differently?

2024-09-05 15:48 UTC, tomlongridge commented on bugsnag-android-core/src/main/java/com/bugsnag/android/SessionStore.kt
> +    File(bugsnagDir, "sessions"),
Are we consistent in when we add a `bugsnag` subdir under the persistence directory?

2024-09-05 16:11 UTC, lemnik commented on bugsnag-android-core/src/main/java/com/bugsnag/android/internal/dag/Provider.kt
> +                    if (isMainThread()) {
No. All of the `Provider` work is always carried out on background threads, so they never wait for the main thread.

2024-09-06 09:55 UTC, tomlongridge commented on bugsnag-android-core/src/main/java/com/bugsnag/android/StorageModule.kt
> +    fun loadUser(initialUser: User): Provider<UserState> = provider {
Discussed IRL - other fields in client will probably go this way in future changes.

2024-09-06 10:27 UTC, tomlongridge commented on bugsnag-android-core/src/main/java/com/bugsnag/android/SessionStore.kt
> +    File(bugsnagDir, "sessions"),
I see now - these are the uses where we go through `migrateLegacyFiles`; the others are using the config value directly.

2024-09-06 11:39 UTC, YYChen01988 requested changes

2024-09-06 11:39 UTC, YYChen01988 commented on bugsnag-android-core/src/main/java/com/bugsnag/android/internal/dag/DependencyModule.kt
> +            override fun invoke(): R = mapping(this@map.get())
Maybe nice to have a note describing what the invoke do and also this class's task?

2024-09-06 14:18 UTC, tomlongridge approved these changes

2024-09-06 14:20 UTC, YYChen01988 approved these changes
LGTM, pending CI

2024-09-09 10:01 UTC, merged